import unittest

from gerodrug_sim.desktop import build_desktop_payload


class DesktopTests(unittest.TestCase):
    def test_build_desktop_payload_without_opening_window(self):
        payload = build_desktop_payload({"participants": 40, "months": 12, "top": 2})

        self.assertEqual(len(payload["candidates"]), 2)
        self.assertEqual(len(payload["trials"]), 2)
        self.assertGreaterEqual(len(payload["endpoints"]), 5)
        self.assertGreaterEqual(len(payload["evidence"]), 5)
        self.assertGreaterEqual(len(payload["software"]), 5)
        self.assertGreaterEqual(len(payload["reprogramming"]), 5)
        self.assertGreaterEqual(len(payload["combinations"]), 2)
        self.assertGreaterEqual(len(payload["tissue_plans"]), 3)
        self.assertGreaterEqual(len(payload["safety_gates"]), 5)
        self.assertGreaterEqual(len(payload["evidence_gaps"]), 5)
        self.assertEqual(payload["asset_summary"]["counts"]["candidate_genes"], 100)
        self.assertEqual(payload["asset_summary"]["counts"]["organizations"], 50)
        self.assertIn("credibility_score", payload["asset_audit"])
        self.assertGreaterEqual(len(payload["diligence_rows"]), 3)
        self.assertGreaterEqual(len(payload["gene_rankings"]), 100)
        self.assertGreaterEqual(len(payload["gene_portfolio"]), 50)
        self.assertGreaterEqual(len(payload["stress_tests"]), 10)
        self.assertGreaterEqual(len(payload["gene_evidence_packs"]), 10)
        self.assertIn("method_version", payload["scoring_method"])
        self.assertGreaterEqual(len(payload["program_milestones"]), 4)
        self.assertGreaterEqual(len(payload["experiment_backlog"]), 10)
        self.assertGreaterEqual(len(payload["partner_shortlist"]), 8)
        self.assertGreaterEqual(len(payload["data_room_checklist"]), 5)
        self.assertEqual(len(payload["organizations"]), 50)
        self.assertIn("evidence_basis", payload["reprogramming"][0])
        self.assertIn("literature_count", payload["reprogramming"][0])
        self.assertIn("validation_plan", payload["combinations"][0])
        self.assertIn("delivery_focus", payload["tissue_plans"][0])
        self.assertIn("stop_triggers", payload["safety_gates"][0])
        self.assertIn("ai_task", payload["evidence_gaps"][0])
        self.assertIn("Asclepius 模拟报告", payload["report"])
        self.assertIn("候选药排名", payload["report"])
        self.assertIn("研发设计补充", payload["report"])
        self.assertIn("部分重编程因子优先级", payload["report"])
        self.assertIn("过程：", payload["report"])
        self.assertIn("下一步：", payload["report"])
        self.assertIn("实验草案：", payload["report"])
        self.assertIn("Go/No-Go：", payload["report"])
        self.assertIn("部分重编程组合策略", payload["report"])
        self.assertIn("验证：", payload["report"])
        self.assertIn("组织优先研发路线", payload["report"])
        self.assertIn("安全闸门矩阵", payload["report"])
        self.assertIn("证据缺口与 AI 任务", payload["report"])
        self.assertIn("数据库资产完成度", payload["report"])
        self.assertIn("可信度审计", payload["report"])
        self.assertIn("投资人尽调问答", payload["report"])
        self.assertIn("评分方法卡", payload["report"])
        self.assertIn("基因研发组合分层", payload["report"])
        self.assertIn("权重压力测试", payload["report"])
        self.assertIn("基因证据包摘要", payload["report"])
        self.assertIn("90 天研发里程碑", payload["report"])
        self.assertIn("实验/证据 Backlog", payload["report"])
        self.assertIn("合作方短名单", payload["report"])
        self.assertIn("Data Room 清单", payload["report"])
        self.assertIn("候选基因评分 Top 10", payload["report"])
        self.assertIn("公司/课题组地图样例", payload["report"])
        self.assertIn("软件与数据库路线图", payload["report"])
        self.assertIn("投资人尽调摘要", payload["diligence_report"])
        self.assertIn("证据包样例", payload["diligence_report"])
        self.assertIn("90 天研发里程碑", payload["diligence_report"])
        self.assertIn("实验/证据 Backlog", payload["diligence_report"])


if __name__ == "__main__":
    unittest.main()
